---
title: "EDA"
author: "jonghyuk kim"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_width: 14
    fig_height: 10
    fig.align : 'center'
    toc: yes
    number_sections : yes
    code_folding: show
---

<hr>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)
```

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>


필요 패키지
```{r}
rm(list=ls())
#load packages
library(readxl)
library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)
library(gridExtra)
library(RColorBrewer)
library(ggthemes)
library(fmsb)
library(corrplot)
library(gridExtra)
library(janitor)
library(corrplot)
library(DataExplorer)
library(skimr)
library(kableExtra)
library(moonBook)
library(data.table)
library(scales)
library(ggrepel)
library(ggpubr)
library(lubridate)
options(scipen=999) # turn-off scientific notation like 1e+48
options(tibble.width = Inf)
```

<hr>

<div style="margin-bottom:60px;">
</div>

# **데이터**

```{r, echo=FALSE}
roaming_data <- fread("2. Roaming_data.csv")
news_list <- read_excel("3-1. NewsList.xls")
```

<div style="margin-bottom:90px;">
</div>

```{r, echo=FALSE}
# roaming_data <- roaming_data %>% mutate(iso = ifelse(iso=="tp", "tl", iso))

roaming_data <- roaming_data %>%
  mutate(return = ymd(return) %>% as.POSIXct(),
         arrival = ymd(arrival) %>% as.POSIXct(),
         departure = ymd(departure) %>% as.POSIXct())

nation_code <- fread("국가코드.csv", encoding="UTF-8")

nation_code <- nation_code %>%
  mutate(국명 = str_remove(nation_code$국명, "<") %>% str_trim(side = "left"))

nation_code <- nation_code %>% rename(iso = `2자리`,
                                      nation= 국명) %>% mutate(iso = str_to_lower(iso)) %>% select(-`3자리`)

roaming_data <- left_join(roaming_data, nation_code, by = c("iso" = "iso"))

```

# **귀국 총합**

```{r, echo=FALSE}
roaming_data %>% 
    group_by(return) %>% 
    summarise(count = sum(count)) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="",
         title="Total return count") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),
          plot.title = element_text(hjust = 0.5, face = "bold", size = 17),
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=11,face = "bold"))
```

<div style="margin-bottom:100px;">
</div>

# **귀국 나라별**
```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[1:12]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[13:24]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[25:36]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[37:48]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[49:60]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[61:72]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[73:84]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[85:96]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[97:108]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[109:120]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[121:132]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[133:144]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[145:156]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[157:168]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```

```{r, echo=FALSE}
iso_name <- roaming_data$iso %>% unique()
plot_list <- list()
cnt <- 0

for (i in iso_name[169:174]) {
  cnt <- cnt + 1
  
  plot_list[[i]] <- roaming_data %>% 
    group_by(return, iso, nation) %>% 
    summarise(count = sum(count)) %>% 
    filter(iso == i) %>% 
    ggplot(aes(x=return,y=count)) +
    geom_line() +
    geom_point() +
    scale_x_datetime(date_breaks="7 day", 
                     labels = date_format("%Y-%m-%d")) + 
    theme_bw() +
    labs(x="") +
    theme(axis.text.x = element_text(angle = 90, vjust=0.5, size = 10, face = "bold"),  # rotate x axis text
          panel.grid.minor = element_blank(),
          strip.text.x = element_text(size=15,face = "bold")) +  # turn off minor grid
    facet_grid(~nation)
}

do.call(grid.arrange, c(plot_list, ncol=3))
```